addSbtPlugin("org.scalameta"             % "sbt-scalafmt"              % "2.3.0")
addSbtPlugin("com.github.cb372"          % "sbt-explicit-dependencies" % "0.2.11")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"              % "0.1.10")
// addSbtPlugin("com.eed3si9n" % "sbt-buildinfo" % "x.x.x")
// addSbtPlugin("com.dwijnand" % "sbt-dynver" % "x.x.x")
